name: execution-test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  execution-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: install dependencies
        run: pip install pre-commit

      - name: dummy repo hook execution
        run: |
          mkdir /tmp/dummy-repo
          cd /tmp/dummy-repo
          git init
          
          mkdir ./src
          touch ./src/__init__.py
          mkdir ./src/pkg1
          touch ./src/pkg1/__init__.py
          touch ./src/pkg1/bar.py
          mkdir ./src/pkg2
          touch ./src/pkg2/__init__.py
          touch ./src/pkg2/foo.py

          echo "from ..pkg2 import foo" > ./src/pkg1/bar.py 
          echo "var = 1" > ./src/pkg2/foo.py
          
          cat > .pre-commit-config.yaml <<EOF
          repos:
            - repo: ${{ github.server_url }}/${{ github.repository }}
              rev: ${{ github.sha }}
              hooks:
                - id: shrimport
                  verbose: true
                  args: ['-v', '-R=./src']
          EOF
          
          git add .
          pre-commit install
          
          echo "checking for hook being not skipped"
          set +e
          OUTPUT=$(pre-commit run --all-files --show-diff-on-failure 2>&1)
          set -e

          if echo "$OUTPUT" | grep -q "Skipped"; then
            echo "hook was skipped"
            exit 1
          else
            echo "hook successfully executed (regardless of success/failure)"
          fi
